eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://eureka_admin:secret@localhost:8761/eureka/

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: "admin"
      password: "secret"
eureka:
  instance:
    metadata-map:
      user.name: "admin"
      user.password: "secret"
---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka_admin:secret@eureka-service:8761/eureka/
