spring:
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: greeting-instance
        uri: lb://greeting-instance
        predicates:
        - Path=/greeting/**
        
---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
