spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: greeting-instance
          uri: lb://greeting-instance
          predicates:
            - Path=/greeting/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka_admin:secret@localhost:8761/eureka/
---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka_admin:secret@eureka-service:8761/eureka/
