eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka_admin:secret@localhost:8761/eureka/

---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka_admin:secret@eureka-service:8761/eureka/
