spring:
  security:
    user:
      name: admin
      password: secret

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka_admin:secret@localhost:8761/eureka/
  instance:
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: "admin"
      user.password: "secret"

---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka_admin:secret@eureka-service:8761/eureka/
  instance:
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: "admin"
      user.password: "secret"
