eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
